Tap tester
singer-io/tap-sailthru pull request #1
Opened 2021-05-10 20:05 UTC by pbegle

# Description of change
Adding tap tester.

# Manual QA steps
 - 
 
# Risks
 - I don't really have the ability to run this so not sure that it actually works.
 
# Rollback steps
 - revert this branch

2021-05-11 13:55 UTC, kspeer825 requested changes

2021-05-11 13:55 UTC, kspeer825 commented on tests/base.py
> +from tap_sailthru.discover import get_schemas
Dependencies on the tap code should be avoided at all costs in these tests. It is important that expectations are set separately based on the business logic of the 3rd party application and product requirements, not based on the implementation of those requirements in the tap.

2021-05-11 13:55 UTC, kspeer825 commented on tests/base.py
> +        return {table: metadata[table][0]['metadata'] for table in metadata.keys()}
This metadata should be explicitly written out using the constants at the top of the class, not set based off of the tap implementation.

2021-05-11 13:55 UTC, kspeer825 commented on tests/base.py
> +            'api_secret': os.environ['TAP_SAILTHRU_API_SECRET'],
I believe the key-value pairs set in `get_properties` and `get_credentials` should be mutually exclusive. They should be dropped here if they are in fact credentials.

2021-05-13 20:05 UTC, pbegle commented
@kspeer825 I made the changes you requested. Let me know if that looks good now or if there are additional changes.

2021-05-14 11:53 UTC, kspeer825 approved these changes
Thanks @pbegle, looks good.

2021-05-25 15:56 UTC, merged