TDL-17511-Add missing test case, TDL-17522-Fix typos in the fields
singer-io/tap-sailthru pull request #5
Opened 2022-01-31 10:42 UTC by umangagrawal-crest

# Description of change
TDL-17511 Add missing tap tester tests

Added following below integration tests:

- Start Date Test
- Automatic Fields Test
- All Fields Test
- Bookmark Test
- Discovery Test
**NOTE:** Pagination test cases are not written as no stream is using pagination.

TDL-17522 FIx typos in the  fields

- Updated the field name `largest_purchase item_price` in the schema file of blast_save_list stream.
- Updated the streams.py file to use the correct replication_key.

**NOTE:** 

- Removed the test_sync_canary.py file.
- Added the config.yml file 
- The CircleCI plan is not configured for this tap.

# Manual QA steps
 - 
 
# Risks
 -  No risks
 
# Rollback steps
 - revert this branch

2022-01-31 11:07 UTC, umangagrawal-crest commented on tap_sailthru/schemas/blast_save_list.json
> +    "largest_purchase_item_price": {
The data was not collected for this field  `largest_purchase_item_price` due to a typo issue. So corrected the field name.

2022-01-31 11:28 UTC, umangagrawal-crest commented on tap_sailthru/streams.py
> +                transform_keys_to_snake_case(record)
Transforming record from camel_case to snake_case before retrieving a value of replication key from the record as replication_key is defined in snake_case in the  [schema file](https://github.com/singer-io/tap-sailthru/blob/main/tap_sailthru/schemas/purchase_log.json#L7)

2022-01-31 11:33 UTC, umangagrawal-crest commented on tap_sailthru/streams.py
> +                transform_keys_to_snake_case(record)
Transforming record from camel_case to snake_case before retrieving a value of replication key from the record as replication_key is defined in snake_case in the schema file
https://github.com/singer-io/tap-sailthru/blob/249d3ae35ec1e929152608a78abff3d1f86cb386/tap_sailthru/schemas/purchase_log.json#L6-L13

2022-01-31 11:34 UTC, umangagrawal-crest commented on tap_sailthru/streams.py
> +    valid_replication_keys = ['date']
As mentioned above, syncing with the schema file.

2022-02-02 06:12 UTC, savan-chovatiya approved these changes

2022-02-02 12:00 UTC, dbshah1212 commented on tap_sailthru/streams.py
> +                transform_keys_to_snake_case(record)
Can you please attach the card related to this bug? To explain this issue in detail.

2022-02-02 12:35 UTC, umangagrawal-crest commented on tap_sailthru/streams.py
> +                transform_keys_to_snake_case(record)
Here is the bug: https://jira.talendforge.org/browse/TDL-17522

2022-02-02 13:10 UTC, dbshah1212 approved these changes

2022-02-04 07:35 UTC, karanpanchal-crest approved these changes

2022-02-14 18:31 UTC, kspeer825 requested changes

2022-02-15 08:40 UTC, harshpatel4crest commented on tests/base.py
> +import singer
Removed.

2022-02-15 09:38 UTC, harshpatel4crest commented on tests/test_bookmark.py
> +        menagerie.set_state(conn_id, new_states)
@kspeer825 Updated the state between the sync and set a date smaller then bookmark value.

2022-02-22 18:33 UTC, kspeer825 approved these changes

2022-02-24 05:06 UTC, merged