TDL-17516: Add custom exception handling
singer-io/tap-sailthru pull request #8
Opened 2022-02-02 05:18 UTC by harshpatel4crest

# Description of change
TDL-17516: Add custom exception handling
- Added error handling based on the [document](https://getstarted.sailthru.com/developers/api-basics/responses/)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-02-02 07:00 UTC, savan-chovatiya requested changes

2022-02-02 09:05 UTC, harshpatel4crest commented on tap_sailthru/client.py
> +        "message": "The resource you have specified cannot be found. Either the accounts provided are invalid or you do not have access to the Ad Account."
Updated error message.

2022-02-02 09:08 UTC, harshpatel4crest commented on tap_sailthru/client.py
> +
As this is an error, we should raise it instead of returning the response. As the Tap is expecting data from the response, it may break at another location.

2022-02-02 10:54 UTC, dbshah1212 commented on tap_sailthru/client.py
> +        "raise_exception": SailthruServer5xxError,
Do define 5xx and 500 differently. Make 500 a sub-class of 5xx because it is an internal server error specifically.

2022-02-02 10:55 UTC, dbshah1212 commented on tap_sailthru/client.py
> +    if status_code == 400 and error_code == 99:
Please add comments for this specific scenario.

2022-02-02 10:57 UTC, dbshah1212 commented on tap_sailthru/client.py
> +def raise_for_error(response):
Provide function comments for all functions.

2022-02-02 10:59 UTC, dbshah1212 commented on tests/unittests/test_error_handling.py
> +from unittest import mock
Do provide test function comment

2022-02-02 11:50 UTC, harshpatel4crest commented on tests/unittests/test_error_handling.py
> +from unittest import mock
Added.

2022-02-02 11:50 UTC, harshpatel4crest commented on tap_sailthru/client.py
> +def raise_for_error(response):
Added.

2022-02-02 11:51 UTC, harshpatel4crest commented on tap_sailthru/client.py
> +    if status_code == 400 and error_code == 99:
This condition was already present, we have just changed the locaiton.

2022-02-02 11:51 UTC, harshpatel4crest commented on tap_sailthru/client.py
> +        "raise_exception": SailthruServer5xxError,
Done.

2022-02-02 12:02 UTC, dbshah1212 commented on tap_sailthru/client.py
> +    if status_code == 400 and error_code == 99:
Still better to add the comment for future developers.

2022-02-04 07:30 UTC, karanpanchal-crest approved these changes

2022-02-07 06:26 UTC, harshpatel4crest commented on tap_sailthru/client.py
> +    if status_code == 400 and error_code == 99:
We did not find any doc regarding this, not sure why it was implemented before.

2022-02-11 09:32 UTC, KrisPersonal approved these changes

2022-02-14 22:03 UTC, kspeer825 approved these changes

2022-02-24 05:50 UTC, merged